# Generated by Django 5.1.5 on 2025-01-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_category_contact_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
